[package]
name = "kclvm-loader"
version = "0.10.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.0"
anyhow = "1.0"

kclvm-ast = {path = "../ast"}
kclvm-ast-pretty = { path = "../ast_pretty" }
kclvm-parser = {path = "../parser"}
kclvm-sema = {path = "../sema"}
kclvm-error = {path = "../error"}
kclvm-query = {path = "../query"}
kclvm-utils = {path = "../utils"}
maplit = "1.0.2"

[dev-dependencies]
insta = "1.8.0"
