[package]
name = "kclvm-ast"
version = "0.4.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_base_span = "0.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

kclvm-span = {path = "../span", version = "0.4.5"}

[dev-dependencies]
kclvm-parser = {path = "../parser", version = "0.4.5"}
