[package]
name = "kcl-language-server"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
env_logger = "0.11.2"
ropey = "1.3.2"
tokio-test = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
dashmap = "5.1.0"
log = "0.4.14"
im-rc = "15.0.0"
rustc_lexer = "0.1.0"
clap = { version = "4.3.0", features = ["string"] }
maplit = "1.0.2"
compiler_base_session.workspace = true

kcl-tools = { path = "../../../tools" }
kcl-error.workspace = true
kcl-config.workspace = true
kcl-driver.workspace = true
kcl-parser.workspace = true
kcl-sema.workspace = true
kcl-ast.workspace = true
kcl-utils.workspace = true
kcl-version.workspace = true
kcl-query.workspace = true
kcl-span.workspace = true
kcl-primitives.workspace = true

lsp-server = { version = "0.7.7", default-features = false }
anyhow = { version = "1.0", default-features = false, features = ["std"] }
crossbeam-channel = { version = "0.5.7", default-features = false }
ra_ap_vfs = "0.0.149"
ra_ap_vfs-notify = "0.0.149"
lsp-types = { version = "0.93.0", features = ["proposed"] }
threadpool = { version = "1.8.1", default-features = false }
salsa = { version = "0.16.1", default-features = false }
serde_json = { version = "1.0", default-features = false }
parking_lot = { version = "0.12.0", default-features = false }
rustc-hash = { version = "1.1.0", default-features = false }
proc_macro_crate = { path = "../../benches/proc_macro_crate" }
notify = "7.0.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependencies]
insta = "1.8.0"
