[package]
name = "kcl-version"
version.workspace = true
edition.workspace = true

[build-dependencies]
vergen = { version = "9.0.0", features = ["rustc"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
