[package]
name = "kcl-span"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_base_span.workspace = true

kcl-macros.workspace = true
scoped-tls = "1.0"
parking_lot = "0.11"
