[package]
name = "compiler-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler-base-diagnostic = {path = "./error/diagnostic", version = "0.1.0"}
