[package]
name = "kclvm-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.0"
fancy-regex = "0.7.1"

kclvm-ast = {path = "../ast", version = "0.1.0"}
