[package]
name = "kclvm-tools"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.0"
fancy-regex = "0.7.1"
walkdir = "2"
anyhow = "1.0"
compiler_base_session = {path = "../../compiler_base/session"}

rustc_lexer = "0.1.0"
kclvm-ast = {path = "../ast"}
kclvm-error = {path = "../error"}
kclvm-parser = {path = "../parser"}
kclvm-sema = {path = "../sema"}
kclvm-config = {path = "../config"}
kclvm-ast-pretty = {path = "../ast_pretty"}
kclvm-query = {path = "../query"}
kclvm-runner = {path = "../runner"}
kclvm-runtime = {path = "../runtime"}
kclvm-driver = {path = "../driver"}

serde_json = "1.0.85"
serde_yaml = "0.9.13"
once_cell = "1.15.0"
regex = "1.3"

[dev-dependencies]
pretty_assertions = "1.2.1"
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false


