[package]
name = "kclvm-capi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "kclvm_capi"

[dependencies]
protobuf = "3.1.0"
serde_json = "1.0"
serde_yaml = "0.9.2"
protobuf-json-mapping = "3.1.0"
serde = { version = "1", features = ["derive"] }

kclvm-runner = {path = "../runner", version = "0.1.0"}
kclvm-parser = {path = "../parser", version = "0.1.0"}
kclvm-ast = {path = "../ast", version = "0.1.0"}
kclvm-runtime = {path = "../runtime", version = "0.1.0"}
kclvm-tools = {path = "../tools", version= "0.1.0" }

[dev-dependencies]
criterion = "0.3"

[build_dependencies]
protobuf-codegen= "3.1.0"
protoc-bin-vendored = "3.0.0"

[profile.release]
rpath = true
panic = "unwind"
opt-level = "z"  # Optimize for size.
lto = true