[package]
name = "kclvm-span"
version = "0.8.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_base_span = "0.1.2" 

kclvm-macros = { path = "../macros" }
scoped-tls = "1.0"
parking_lot = "0.11"
