[package]
name = "prost-wkt-types"
version = "0.4.1"
authors = ["fdeantoni <fdeantoni@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/fdeantoni/prost-wkt"
description = "Helper crate for prost to allow JSON serialization and deserialization of Well Known Types."
readme = "../README.md"
documentation = "https://docs.rs/prost-wkt"
keywords = ["protobuf", "serde", "json"]
categories = ["encoding"]
edition = "2021"

[lib]
doctest = false

[features]
default = ["std"]
std = []

[dependencies]
prost-wkt = { version = "0.4.1", path = ".." }
prost = "0.11.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", default-features = false, features = ["serde"] }

[build-dependencies]
protoc-bin-vendored = "3.0.0"
prost = "0.11.6"
prost-types = "0.11.5"
prost-build = "0.11.5"
prost-wkt-build = { version = "0.4.1", path = "../wkt-build" }
regex = "1"
