kcl_cli_configs:
  files:
    - ../main.k
    - ./before/base.k
    - ./main.k
    - ./sub/sub.k
  disable_none: false
  strict_range_check: false
  debug: false
kcl_options:
  - key: app-name
    value: kcl
  - key: image
    value: kcl:v0.0.1
