[package]
name = "kclvm_runtime_internal_macros"
version = "0.5.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"

[lib]
proc-macro = true

[features]
default = []
