[package]
name = "json_minimal"
version = "0.1.3"
authors = ["36den"]
edition = "2021"
description = "A minimal json crate."
license = "MIT OR Apache-2.0"
keywords = ["json","minimal"]
categories = ["encoding"]
repository = "https://github.com/36den/json_minimal-rust"
readme = "README.md"

[dependencies]
