[package]
name = "kclvm-version"
version = "0.10.0"
edition = "2021"

[build-dependencies]
vergen-gitcl = { version = "1.0.0", features = ["rustc"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
