name: build-and-test-compiler-base
on:
  push:
    paths:
      - 'compiler_base/**'
  pull_request:
    paths:
      - 'compiler_base/**'

jobs:
  check-fmt:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.91
          override: true
          components: clippy, rustfmt

  test-codecov-lcov:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.91
          override: true
          components: clippy, rustfmt
      - name: Format
        working-directory: ./compiler_base
        run: cargo clippy --workspace --all-features --benches --examples --tests -- -D warnings
      - name: Lint
        working-directory: ./compiler_base
        run: cargo fmt --all -- --check
      - name: Unit test
        working-directory: ./compiler_base
        run: cargo test -r --workspace --all-features
