name: Build and Test on Linux ARCH64
on:
  push:
    branches:
     - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/linux
    name: Test
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      # Prerequisite

      - name: Install Python3 (for Grammar test)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl make
          sudo apt-get install python3 python3-pip -y
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.91
          override: true
          components: clippy, rustfmt
      - name: Code format check
        run: cargo fmt --check
        shell: bash
      - name: chmod
        run: |
          chmod -R 777 crates
      - name: Code clippy check
        run: make lint-all
        shell: bash
      - name: Grammar test
        run: export PATH=$PATH:$PWD/_build/dist/linux/core && make && make test-grammar
        shell: bash
      - name: Runtime test
        run: export PATH=$PATH:$PWD/_build/dist/linux/core && make test-runtime
        shell: bash
      - name: Install KCL CLI
        run: |
          go install kcl-lang.io/cli/cmd/kcl@main
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH
      - name: Unit test
        run: export PATH=$PATH:$PWD/_build/dist/linux/core && make test
        shell: bash
      
      - name: Release
        run: export PATH=$PATH:$PWD/_build/dist/linux/core && make release
        shell: bash

      - name: Read VERSION file
        id: read_version
        run: |
          VERSION=$(cargo pkgid -p kcl-api | cut -d'@' -f2)
          echo "VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Rename artifact name with version
        run: sudo mv -f _build/dist/linux/kcl-latest-linux-arm64.tar.gz _build/dist/linux/kcl-${{ env.VERSION }}-linux-arm64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: kcl-${{ env.VERSION }}-linux-arm64
          if-no-files-found: error
          path: _build/dist/linux/kcl-${{ env.VERSION }}-linux-arm64.tar.gz
