[package]
name = "kclvm-sema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.9", features = ["macros"] }
ahash = "0.7.2"
indexmap = "1.0"
bit-set = "0.5.0"
bitflags = "1.2.1"
once_cell = "1.5.2"
fancy-regex = "0.7.1"
unicode_names2 = "0.4"
petgraph = "0.6.0"
kclvm-ast = {path = "../ast", version = "0.1.0"}
kclvm-runtime = {path = "../runtime", version = "0.1.0"}
kclvm-error = {path = "../error", version = "0.1.0"}
kclvm-span = {path = "../span", version = "0.1.0"}

[dev-dependencies]
kclvm-parser = {path = "../parser", version = "0.1.0"}
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
